version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: soccer-db
    env_file:
      - ./app/backend/.env
    volumes:
      - db-data:/var/lib/mysql
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh

  backend:
    container_name: soccer-backend
    build:
      context: .
      target: backend
    ports:
      - 8080:8080
    env_file:
      - ./app/backend/.env
    depends_on:
      - db

  frontend:
    container_name: soccer-frontend
    build:
      context: .
      target: frontend
    ports:
      - "5173:80"
    env_file:
      - ./app/frontend/.env

volumes:
  db-data:
